# Site settings
title: music
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Website to overview the music composed by Jaap Cramer.
baseurl: "/music" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jrcramer

# Build settings
markdown: kramdown
#collections:
#- works