# Site settings
title: music
#email: your-email@domain.com
description: Showcasing music composed by Jaap Cramer.
baseurl: "/music" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jaapcramer
facebook: jaapcramer
github_username:  jrcramer

# Build settings
markdown: kramdown
#collections:
#- works